<?php

/**
 * Handles the creation of table `{{%municipalities}}`.
 */
class m221129_131320_create_municipalities_table extends \app\migrations\Migration
{
    public function tableName()
    {
        return '{{%municipalities}}';
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable($this->tableName(), $this->attributes([
            'name' => $this->string(50),
            'province_no' => $this->tinyInteger(2),
        ]));

        $this->seed();
    }

    public function seed()
    {
        $rows = [];

        foreach($this->data() as $data) {
            list($name, $province_no) = $data;

            $rows[] = [
                'name' => $name,
                'province_no' => $province_no,
            ];
        }

        if ($rows) {
            $arr = array_chunk($rows, 1000);
            $columns = array_keys($rows[0]);
            foreach ($arr as $r) {
                $this->batchInsert($this->tableName(), $columns, $r);
            }
        }
    }

    public function data()
    {
        return [
            array('PASUQUIN', 28),
            array('PIDDIG', 28),
            array('PINILI', 28),
            array('SAN NICOLAS', 28),
            array('SARRAT', 28),
            array('SOLSONA', 28),
            array('VINTAR', 28),
            array('ALILEM', 29),
            array('BANAYOYO', 29),
            array('BANTAY', 29),
            array('BURGOS', 29),
            array('CABUGAO', 29),
            array('CITY OF CANDON', 29),
            array('CAOAYAN', 29),
            array('CERVANTES', 29),
            array('GALIMUYOD', 29),
            array('GREGORIO DEL PILAR', 29),
            array('LIDLIDDA', 29),
            array('MAGSINGAL', 29),
            array('NAGBUKEL', 29),
            array('NARVACAN', 29),
            array('QUIRINO', 29),
            array('SALCEDO', 29),
            array('SAN EMILIO', 29),
            array('SAN ESTEBAN', 29),
            array('SAN ILDEFONSO', 29),
            array('SAN JUAN', 29),
            array('SAN VICENTE', 29),
            array('SANTA', 29),
            array('SANTA CATALINA', 29),
            array('SANTA CRUZ', 29),
            array('SANTA LUCIA', 29),
            array('SANTA MARIA', 29),
            array('SANTIAGO', 29),
            array('SANTO DOMINGO', 29),
            array('SIGAY', 29),
            array('SINAIT', 29),
            array('SUGPON', 29),
            array('SUYO', 29),
            array('TAGUDIN', 29),
            array('CITY OF VIGAN', 29),
            array('AGOO', 33),
            array('ARINGAY', 33),
            array('BACNOTAN', 33),
            array('BAGULIN', 33),
            array('BALAOAN', 33),
            array('BANGAR', 33),
            array('BAUANG', 33),
            array('BURGOS', 33),
            array('CABA', 33),
            array('LUNA', 33),
            array('NAGUILIAN', 33),
            array('PUGO', 33),
            array('ROSARIO', 33),
            array('CITY OF SAN FERNANDO', 33),
            array('SAN GABRIEL', 33),
            array('SAN JUAN', 33),
            array('SANTO TOMAS', 33),
            array('SANTOL', 33),
            array('SUDIPEN', 33),
            array('TUBAO', 33),
            array('AGNO', 55),
            array('AGUILAR', 55),
            array('CITY OF ALAMINOS', 55),
            array('ALCALA', 55),
            array('ANDA', 55),
            array('ASINGAN', 55),
            array('BALUNGAO', 55),
            array('BANI', 55),
            array('BASISTA', 55),
            array('BAUTISTA', 55),
            array('BAYAMBANG', 55),
            array('BINALONAN', 55),
            array('BINMALEY', 55),
            array('BOLINAO', 55),
            array('BUGALLON', 55),
            array('BURGOS', 55),
            array('CALASIAO', 55),
            array('DAGUPAN CITY', 55),
            array('DASOL', 55),
            array('INFANTA', 55),
            array('LABRADOR', 55),
            array('LINGAYEN', 55),
            array('MABINI', 55),
            array('MALASIQUI', 55),
            array('MANAOAG', 55),
            array('MANGALDAN', 55),
            array('MANGATAREM', 55),
            array('MAPANDAN', 55),
            array('NATIVIDAD', 55),
            array('POZZORUBIO', 55),
            array('ROSALES', 55),
            array('SAN CARLOS CITY', 55),
            array('SAN FABIAN', 55),
            array('SAN JACINTO', 55),
            array('SAN MANUEL', 55),
            array('SAN NICOLAS', 55),
            array('SAN QUINTIN', 55),
            array('SANTA BARBARA', 55),
            array('SANTA MARIA', 55),
            array('SANTO TOMAS', 55),
            array('SISON', 55),
            array('SUAL', 55),
            array('TAYUG', 55),
            array('UMINGAN', 55),
            array('URBIZTONDO', 55),
            array('CITY OF URDANETA', 55),
            array('VILLASIS', 55),
            array('LAOAC', 55),
            array('ADAMS', 28),
            array('BACARRA', 28),
            array('BADOC', 28),
            array('BANGUI', 28),
            array('BATAC', 28),
            array('BURGOS', 28),
            array('CARASI', 28),
            array('CURRIMAO', 28),
            array('DINGRAS', 28),
            array('DUMALNEG', 28),
            array('BANNA', 28),
            array('LAOAG CITY', 28),
            array('MARCOS', 28),
            array('NUEVA ERA', 28),
            array('PAGUDPUD', 28),
            array('PAOAY', 28),
            array('BASCO', 9),
            array('ITBAYAT', 9),
            array('IVANA', 9),
            array('MAHATAO', 9),
            array('SABTANG', 9),
            array('UYUGAN', 9),
            array('ABULUG', 15),
            array('ALCALA', 15),
            array('ALLACAPAN', 15),
            array('AMULUNG', 15),
            array('APARRI', 15),
            array('BAGGAO', 15),
            array('BALLESTEROS', 15),
            array('BUGUEY', 15),
            array('CALAYAN', 15),
            array('CAMALANIUGAN', 15),
            array('CLAVERIA', 15),
            array('ENRILE', 15),
            array('GATTARAN', 15),
            array('GONZAGA', 15),
            array('IGUIG', 15),
            array('LAL-LO', 15),
            array('LASAM', 15),
            array('PAMPLONA', 15),
            array('PEÑABLANCA', 15),
            array('PIAT', 15),
            array('RIZAL', 15),
            array('SANCHEZ-MIRA', 15),
            array('SANTA ANA', 15),
            array('SANTA PRAXEDES', 15),
            array('SANTA TERESITA', 15),
            array('SANTO NIÑO', 15),
            array('SOLANA', 15),
            array('TUAO', 15),
            array('TUGUEGARAO CITY', 15),
            array('ALICIA', 31),
            array('ANGADANAN', 31),
            array('AURORA', 31),
            array('BENITO SOLIVEN', 31),
            array('BURGOS', 31),
            array('CABAGAN', 31),
            array('CABATUAN', 31),
            array('CITY OF CAUAYAN', 31),
            array('CORDON', 31),
            array('DINAPIGUE', 31),
            array('DIVILACAN', 31),
            array('ECHAGUE', 31),
            array('GAMU', 31),
            array('ILAGAN', 31),
            array('JONES', 31),
            array('LUNA', 31),
            array('MACONACON', 31),
            array('DELFIN ALBANO', 31),
            array('MALLIG', 31),
            array('NAGUILIAN', 31),
            array('PALANAN', 31),
            array('QUEZON', 31),
            array('QUIRINO', 31),
            array('RAMON', 31),
            array('REINA MERCEDES', 31),
            array('ROXAS', 31),
            array('SAN AGUSTIN', 31),
            array('SAN GUILLERMO', 31),
            array('SAN ISIDRO', 31),
            array('SAN MANUEL', 31),
            array('SAN MARIANO', 31),
            array('SAN MATEO', 31),
            array('SAN PABLO', 31),
            array('SANTA MARIA', 31),
            array('CITY OF SANTIAGO', 31),
            array('SANTO TOMAS', 31),
            array('TUMAUINI', 31),
            array('AMBAGUIO', 50),
            array('ARITAO', 50),
            array('BAGABAG', 50),
            array('BAMBANG', 50),
            array('BAYOMBONG', 50),
            array('DIADI', 50),
            array('DUPAX DEL NORTE', 50),
            array('DUPAX DEL SUR', 50),
            array('KASIBU', 50),
            array('KAYAPA', 50),
            array('QUEZON', 50),
            array('SANTA FE', 50),
            array('SOLANO', 50),
            array('VILLAVERDE', 50),
            array('ALFONSO CASTANEDA', 50),
            array('AGLIPAY', 57),
            array('CABARROGUIS', 57),
            array('DIFFUN', 57),
            array('MADDELA', 57),
            array('SAGUDAY', 57),
            array('NAGTIPUNAN', 57),
            array('ABUCAY', 8),
            array('BAGAC', 8),
            array('CITY OF BALANGA', 8),
            array('DINALUPIHAN', 8),
            array('HERMOSA', 8),
            array('LIMAY', 8),
            array('MARIVELES', 8),
            array('MORONG', 8),
            array('ORANI', 8),
            array('ORION', 8),
            array('PILAR', 8),
            array('SAMAL', 8),
            array('ANGAT', 14),
            array('BALAGTAS', 14),
            array('BALIUAG', 14),
            array('BOCAUE', 14),
            array('BULACAN', 14),
            array('BUSTOS', 14),
            array('CALUMPIT', 14),
            array('GUIGUINTO', 14),
            array('HAGONOY', 14),
            array('CITY OF MALOLOS', 14),
            array('MARILAO', 14),
            array('CITY OF MEYCAUAYAN', 14),
            array('NORZAGARAY', 14),
            array('OBANDO', 14),
            array('PANDI', 14),
            array('PAOMBONG', 14),
            array('PLARIDEL', 14),
            array('PULILAN', 14),
            array('SAN ILDEFONSO', 14),
            array('CITY OF SAN JOSE DEL MONTE', 14),
            array('SAN MIGUEL', 14),
            array('SAN RAFAEL', 14),
            array('SANTA MARIA', 14),
            array('DOÑA REMEDIOS TRINIDAD', 14),
            array('ALIAGA', 49),
            array('BONGABON', 49),
            array('CABANATUAN CITY', 49),
            array('CABIAO', 49),
            array('CARRANGLAN', 49),
            array('CUYAPO', 49),
            array('GABALDON', 49),
            array('CITY OF GAPAN', 49),
            array('GENERAL MAMERTO NATIVIDAD', 49),
            array('GENERAL TINIO', 49),
            array('GUIMBA', 49),
            array('JAEN', 49),
            array('LAUR', 49),
            array('LICAB', 49),
            array('LLANERA', 49),
            array('LUPAO', 49),
            array('SCIENCE CITY OF MUÑOZ', 49),
            array('NAMPICUAN', 49),
            array('PALAYAN CITY', 49),
            array('PANTABANGAN', 49),
            array('PEÑARANDA', 49),
            array('QUEZON', 49),
            array('RIZAL', 49),
            array('SAN ANTONIO', 49),
            array('SAN ISIDRO', 49),
            array('SAN JOSE CITY', 49),
            array('SAN LEONARDO', 49),
            array('SANTA ROSA', 49),
            array('SANTO DOMINGO', 49),
            array('TALAVERA', 49),
            array('TALUGTUG', 49),
            array('ZARAGOZA', 49),
            array('ANGELES CITY', 54),
            array('APALIT', 54),
            array('ARAYAT', 54),
            array('BACOLOR', 54),
            array('CANDABA', 54),
            array('FLORIDABLANCA', 54),
            array('GUAGUA', 54),
            array('LUBAO', 54),
            array('MABALACAT', 54),
            array('MACABEBE', 54),
            array('MAGALANG', 54),
            array('MASANTOL', 54),
            array('MEXICO', 54),
            array('MINALIN', 54),
            array('PORAC', 54),
            array('CITY OF SAN FERNANDO', 54),
            array('SAN LUIS', 54),
            array('SAN SIMON', 54),
            array('SANTA ANA', 54),
            array('SANTA RITA', 54),
            array('SANTO TOMAS', 54),
            array('SASMUAN', 54),
            array('ANAO', 69),
            array('BAMBAN', 69),
            array('CAMILING', 69),
            array('CAPAS', 69),
            array('CONCEPCION', 69),
            array('GERONA', 69),
            array('LA PAZ', 69),
            array('MAYANTOC', 69),
            array('MONCADA', 69),
            array('PANIQUI', 69),
            array('PURA', 69),
            array('RAMOS', 69),
            array('SAN CLEMENTE', 69),
            array('SAN MANUEL', 69),
            array('SANTA IGNACIA', 69),
            array('CITY OF TARLAC', 69),
            array('VICTORIA', 69),
            array('SAN JOSE', 69),
            array('BOTOLAN', 71),
            array('CABANGAN', 71),
            array('CANDELARIA', 71),
            array('CASTILLEJOS', 71),
            array('IBA', 71),
            array('MASINLOC', 71),
            array('OLONGAPO CITY', 71),
            array('PALAUIG', 71),
            array('SAN ANTONIO', 71),
            array('SAN FELIPE', 71),
            array('SAN MARCELINO', 71),
            array('SAN NARCISO', 71),
            array('SANTA CRUZ', 71),
            array('SUBIC', 71),
            array('BALER', 77),
            array('CASIGURAN', 77),
            array('DILASAG', 77),
            array('DINALUNGAN', 77),
            array('DINGALAN', 77),
            array('DIPACULAO', 77),
            array('MARIA AURORA', 77),
            array('SAN LUIS', 77),
            array('AGONCILLO', 10),
            array('ALITAGTAG', 10),
            array('BALAYAN', 10),
            array('BALETE', 10),
            array('BATANGAS CITY', 10),
            array('BAUAN', 10),
            array('CALACA', 10),
            array('CALATAGAN', 10),
            array('CUENCA', 10),
            array('IBAAN', 10),
            array('LAUREL', 10),
            array('LEMERY', 10),
            array('LIAN', 10),
            array('LIPA CITY', 10),
            array('LOBO', 10),
            array('MABINI', 10),
            array('MALVAR', 10),
            array('MATAASNAKAHOY', 10),
            array('NASUGBU', 10),
            array('PADRE GARCIA', 10),
            array('ROSARIO', 10),
            array('SAN JOSE', 10),
            array('SAN JUAN', 10),
            array('SAN LUIS', 10),
            array('SAN NICOLAS', 10),
            array('SAN PASCUAL', 10),
            array('SANTA TERESITA', 10),
            array('SANTO TOMAS', 10),
            array('TAAL', 10),
            array('TALISAY', 10),
            array('CITY OF TANAUAN', 10),
            array('TAYSAN', 10),
            array('TINGLOY', 10),
            array('TUY', 10),
            array('ALFONSO', 21),
            array('AMADEO', 21),
            array('BACOOR', 21),
            array('CARMONA', 21),
            array('CAVITE CITY', 21),
            array('DASMARIÑAS', 21),
            array('GENERAL EMILIO AGUINALDO', 21),
            array('GENERAL TRIAS', 21),
            array('IMUS', 21),
            array('INDANG', 21),
            array('KAWIT', 21),
            array('MAGALLANES', 21),
            array('MARAGONDON', 21),
            array('MENDEZ', 21),
            array('NAIC', 21),
            array('NOVELETA', 21),
            array('ROSARIO', 21),
            array('SILANG', 21),
            array('TAGAYTAY CITY', 21),
            array('TANZA', 21),
            array('TERNATE', 21),
            array('TRECE MARTIRES CITY', 21),
            array('GEN. MARIANO ALVAREZ', 21),
            array('ALAMINOS', 34),
            array('BAY', 34),
            array('BIÑAN', 34),
            array('CABUYAO', 34),
            array('CITY OF CALAMBA', 34),
            array('CALAUAN', 34),
            array('CAVINTI', 34),
            array('FAMY', 34),
            array('KALAYAAN', 34),
            array('LILIW', 34),
            array('LOS BAÑOS', 34),
            array('LUISIANA', 34),
            array('LUMBAN', 34),
            array('MABITAC', 34),
            array('MAGDALENA', 34),
            array('MAJAYJAY', 34),
            array('NAGCARLAN', 34),
            array('PAETE', 34),
            array('PAGSANJAN', 34),
            array('PAKIL', 34),
            array('PANGIL', 34),
            array('PILA', 34),
            array('RIZAL', 34),
            array('SAN PABLO CITY', 34),
            array('SAN PEDRO', 34),
            array('SANTA CRUZ', 34),
            array('SANTA MARIA', 34),
            array('CITY OF SANTA ROSA', 34),
            array('SINILOAN', 34),
            array('VICTORIA', 34),
            array('AGDANGAN', 56),
            array('ALABAT', 56),
            array('ATIMONAN', 56),
            array('BUENAVISTA', 56),
            array('BURDEOS', 56),
            array('CALAUAG', 56),
            array('CANDELARIA', 56),
            array('CATANAUAN', 56),
            array('DOLORES', 56),
            array('GENERAL LUNA', 56),
            array('GENERAL NAKAR', 56),
            array('GUINAYANGAN', 56),
            array('GUMACA', 56),
            array('INFANTA', 56),
            array('JOMALIG', 56),
            array('LOPEZ', 56),
            array('LUCBAN', 56),
            array('LUCENA CITY', 56),
            array('MACALELON', 56),
            array('MAUBAN', 56),
            array('MULANAY', 56),
            array('PADRE BURGOS', 56),
            array('PAGBILAO', 56),
            array('PANUKULAN', 56),
            array('PATNANUNGAN', 56),
            array('PEREZ', 56),
            array('PITOGO', 56),
            array('PLARIDEL', 56),
            array('POLILLO', 56),
            array('QUEZON', 56),
            array('REAL', 56),
            array('SAMPALOC', 56),
            array('SAN ANDRES', 56),
            array('SAN ANTONIO', 56),
            array('SAN FRANCISCO', 56),
            array('SAN NARCISO', 56),
            array('SARIAYA', 56),
            array('TAGKAWAYAN', 56),
            array('TAYABAS', 56),
            array('TIAONG', 56),
            array('UNISAN', 56),
            array('ANGONO', 58),
            array('CITY OF ANTIPOLO', 58),
            array('BARAS', 58),
            array('BINANGONAN', 58),
            array('CAINTA', 58),
            array('CARDONA', 58),
            array('JALA-JALA', 58),
            array('RODRIGUEZ', 58),
            array('MORONG', 58),
            array('PILILLA', 58),
            array('SAN MATEO', 58),
            array('TANAY', 58),
            array('TAYTAY', 58),
            array('TERESA', 58),
            array('BACACAY', 5),
            array('CAMALIG', 5),
            array('DARAGA', 5),
            array('GUINOBATAN', 5),
            array('JOVELLAR', 5),
            array('LEGAZPI CITY', 5),
            array('LIBON', 5),
            array('CITY OF LIGAO', 5),
            array('MALILIPOT', 5),
            array('MALINAO', 5),
            array('MANITO', 5),
            array('OAS', 5),
            array('PIO DURAN', 5),
            array('POLANGUI', 5),
            array('RAPU-RAPU', 5),
            array('SANTO DOMINGO', 5),
            array('CITY OF TABACO', 5),
            array('TIWI', 5),
            array('BASUD', 16),
            array('CAPALONGA', 16),
            array('DAET', 16),
            array('SAN LORENZO RUIZ', 16),
            array('JOSE PANGANIBAN', 16),
            array('LABO', 16),
            array('MERCEDES', 16),
            array('PARACALE', 16),
            array('SAN VICENTE', 16),
            array('SANTA ELENA', 16),
            array('TALISAY', 16),
            array('VINZONS', 16),
            array('BAAO', 17),
            array('BALATAN', 17),
            array('BATO', 17),
            array('BOMBON', 17),
            array('BUHI', 17),
            array('BULA', 17),
            array('CABUSAO', 17),
            array('CALABANGA', 17),
            array('CAMALIGAN', 17),
            array('CANAMAN', 17),
            array('CARAMOAN', 17),
            array('DEL GALLEGO', 17),
            array('GAINZA', 17),
            array('GARCHITORENA', 17),
            array('GOA', 17),
            array('IRIGA CITY', 17),
            array('LAGONOY', 17),
            array('LIBMANAN', 17),
            array('LUPI', 17),
            array('MAGARAO', 17),
            array('MILAOR', 17),
            array('MINALABAC', 17),
            array('NABUA', 17),
            array('NAGA CITY', 17),
            array('OCAMPO', 17),
            array('PAMPLONA', 17),
            array('PASACAO', 17),
            array('PILI', 17),
            array('PRESENTACION', 17),
            array('RAGAY', 17),
            array('SAGÑAY', 17),
            array('SAN FERNANDO', 17),
            array('SAN JOSE', 17),
            array('SIPOCOT', 17),
            array('SIRUMA', 17),
            array('TIGAON', 17),
            array('TINAMBAC', 17),
            array('BAGAMANOC', 20),
            array('BARAS', 20),
            array('BATO', 20),
            array('CARAMORAN', 20),
            array('GIGMOTO', 20),
            array('PANDAN', 20),
            array('PANGANIBAN', 20),
            array('SAN ANDRES', 20),
            array('SAN MIGUEL', 20),
            array('VIGA', 20),
            array('VIRAC', 20),
            array('AROROY', 41),
            array('BALENO', 41),
            array('BALUD', 41),
            array('BATUAN', 41),
            array('CATAINGAN', 41),
            array('CAWAYAN', 41),
            array('CLAVERIA', 41),
            array('DIMASALANG', 41),
            array('ESPERANZA', 41),
            array('MANDAON', 41),
            array('CITY OF MASBATE', 41),
            array('MILAGROS', 41),
            array('MOBO', 41),
            array('MONREAL', 41),
            array('PALANAS', 41),
            array('PIO V. CORPUZ', 41),
            array('PLACER', 41),
            array('SAN FERNANDO', 41),
            array('SAN JACINTO', 41),
            array('SAN PASCUAL', 41),
            array('USON', 41),
            array('BARCELONA', 62),
            array('BULAN', 62),
            array('BULUSAN', 62),
            array('CASIGURAN', 62),
            array('CASTILLA', 62),
            array('DONSOL', 62),
            array('GUBAT', 62),
            array('IROSIN', 62),
            array('JUBAN', 62),
            array('MAGALLANES', 62),
            array('MATNOG', 62),
            array('PILAR', 62),
            array('PRIETO DIAZ', 62),
            array('SANTA MAGDALENA', 62),
            array('CITY OF SORSOGON', 62),
            array('ALTAVAS', 4),
            array('BALETE', 4),
            array('BANGA', 4),
            array('BATAN', 4),
            array('BURUANGA', 4),
            array('IBAJAY', 4),
            array('KALIBO', 4),
            array('LEZO', 4),
            array('LIBACAO', 4),
            array('MADALAG', 4),
            array('MAKATO', 4),
            array('MALAY', 4),
            array('MALINAO', 4),
            array('NABAS', 4),
            array('NEW WASHINGTON', 4),
            array('NUMANCIA', 4),
            array('TANGALAN', 4),
            array('ANINI-Y', 6),
            array('BARBAZA', 6),
            array('BELISON', 6),
            array('BUGASONG', 6),
            array('CALUYA', 6),
            array('CULASI', 6),
            array('TOBIAS FORNIER', 6),
            array('HAMTIC', 6),
            array('LAUA-AN', 6),
            array('LIBERTAD', 6),
            array('PANDAN', 6),
            array('PATNONGON', 6),
            array('SAN JOSE', 6),
            array('SAN REMIGIO', 6),
            array('SEBASTE', 6),
            array('SIBALOM', 6),
            array('TIBIAO', 6),
            array('VALDERRAMA', 6),
            array('CUARTERO', 19),
            array('DAO', 19),
            array('DUMALAG', 19),
            array('DUMARAO', 19),
            array('IVISAN', 19),
            array('JAMINDAN', 19),
            array('MA-AYON', 19),
            array('MAMBUSAO', 19),
            array('PANAY', 19),
            array('PANITAN', 19),
            array('PILAR', 19),
            array('PONTEVEDRA', 19),
            array('PRESIDENT ROXAS', 19),
            array('ROXAS CITY', 19),
            array('SAPI-AN', 19),
            array('SIGMA', 19),
            array('TAPAZ', 19),
            array('AJUY', 30),
            array('ALIMODIAN', 30),
            array('ANILAO', 30),
            array('BADIANGAN', 30),
            array('BALASAN', 30),
            array('BANATE', 30),
            array('BAROTAC NUEVO', 30),
            array('BAROTAC VIEJO', 30),
            array('BATAD', 30),
            array('BINGAWAN', 30),
            array('CABATUAN', 30),
            array('CALINOG', 30),
            array('CARLES', 30),
            array('CONCEPCION', 30),
            array('DINGLE', 30),
            array('DUEÑAS', 30),
            array('DUMANGAS', 30),
            array('ESTANCIA', 30),
            array('GUIMBAL', 30),
            array('IGBARAS', 30),
            array('ILOILO CITY', 30),
            array('JANIUAY', 30),
            array('LAMBUNAO', 30),
            array('LEGANES', 30),
            array('LEMERY', 30),
            array('LEON', 30),
            array('MAASIN', 30),
            array('MIAGAO', 30),
            array('MINA', 30),
            array('NEW LUCENA', 30),
            array('OTON', 30),
            array('CITY OF PASSI', 30),
            array('PAVIA', 30),
            array('POTOTAN', 30),
            array('SAN DIONISIO', 30),
            array('SAN ENRIQUE', 30),
            array('SAN JOAQUIN', 30),
            array('SAN MIGUEL', 30),
            array('SAN RAFAEL', 30),
            array('SANTA BARBARA', 30),
            array('SARA', 30),
            array('TIGBAUAN', 30),
            array('TUBUNGAN', 30),
            array('ZARRAGA', 30),
            array('BACOLOD CITY', 45),
            array('BAGO CITY', 45),
            array('BINALBAGAN', 45),
            array('CADIZ CITY', 45),
            array('CALATRAVA', 45),
            array('CANDONI', 45),
            array('CAUAYAN', 45),
            array('ENRIQUE B. MAGALONA', 45),
            array('CITY OF ESCALANTE', 45),
            array('CITY OF HIMAMAYLAN', 45),
            array('HINIGARAN', 45),
            array('HINOBA-AN', 45),
            array('ILOG', 45),
            array('ISABELA', 45),
            array('CITY OF KABANKALAN', 45),
            array('LA CARLOTA CITY', 45),
            array('LA CASTELLANA', 45),
            array('MANAPLA', 45),
            array('MOISES PADILLA', 45),
            array('MURCIA', 45),
            array('PONTEVEDRA', 45),
            array('PULUPANDAN', 45),
            array('SAGAY CITY', 45),
            array('SAN CARLOS CITY', 45),
            array('SAN ENRIQUE', 45),
            array('SILAY CITY', 45),
            array('CITY OF SIPALAY', 45),
            array('CITY OF TALISAY', 45),
            array('TOBOSO', 45),
            array('VALLADOLID', 45),
            array('CITY OF VICTORIAS', 45),
            array('SALVADOR BENEDICTO', 45),
            array('BUENAVISTA', 79),
            array('JORDAN', 79),
            array('NUEVA VALENCIA', 79),
            array('SAN LORENZO', 79),
            array('SIBUNAG', 79),
            array('ALBURQUERQUE', 12),
            array('ALICIA', 12),
            array('ANDA', 12),
            array('ANTEQUERA', 12),
            array('BACLAYON', 12),
            array('BALILIHAN', 12),
            array('BATUAN', 12),
            array('BILAR', 12),
            array('BUENAVISTA', 12),
            array('CALAPE', 12),
            array('CANDIJAY', 12),
            array('CARMEN', 12),
            array('CATIGBIAN', 12),
            array('CLARIN', 12),
            array('CORELLA', 12),
            array('CORTES', 12),
            array('DAGOHOY', 12),
            array('DANAO', 12),
            array('DAUIS', 12),
            array('DIMIAO', 12),
            array('DUERO', 12),
            array('GARCIA HERNANDEZ', 12),
            array('GUINDULMAN', 12),
            array('INABANGA', 12),
            array('JAGNA', 12),
            array('JETAFE', 12),
            array('LILA', 12),
            array('LOAY', 12),
            array('LOBOC', 12),
            array('LOON', 12),
            array('MABINI', 12),
            array('MARIBOJOC', 12),
            array('PANGLAO', 12),
            array('PILAR', 12),
            array('PRES. CARLOS P. GARCIA', 12),
            array('SAGBAYAN', 12),
            array('SAN ISIDRO', 12),
            array('SAN MIGUEL', 12),
            array('SEVILLA', 12),
            array('SIERRA BULLONES', 12),
            array('SIKATUNA', 12),
            array('TAGBILARAN CITY', 12),
            array('TALIBON', 12),
            array('TRINIDAD', 12),
            array('TUBIGON', 12),
            array('UBAY', 12),
            array('VALENCIA', 12),
            array('BIEN UNIDO', 12),
            array('ALCANTARA', 22),
            array('ALCOY', 22),
            array('ALEGRIA', 22),
            array('ALOGUINSAN', 22),
            array('ARGAO', 22),
            array('ASTURIAS', 22),
            array('BADIAN', 22),
            array('BALAMBAN', 22),
            array('BANTAYAN', 22),
            array('BARILI', 22),
            array('BOGO', 22),
            array('BOLJOON', 22),
            array('BORBON', 22),
            array('CARCAR', 22),
            array('CARMEN', 22),
            array('CATMON', 22),
            array('CEBU CITY', 22),
            array('COMPOSTELA', 22),
            array('CONSOLACION', 22),
            array('CORDOBA', 22),
            array('DAANBANTAYAN', 22),
            array('DALAGUETE', 22),
            array('DANAO CITY', 22),
            array('DUMANJUG', 22),
            array('GINATILAN', 22),
            array('LAPU-LAPU CITY', 22),
            array('LILOAN', 22),
            array('MADRIDEJOS', 22),
            array('MALABUYOC', 22),
            array('MANDAUE CITY', 22),
            array('MEDELLIN', 22),
            array('MINGLANILLA', 22),
            array('MOALBOAL', 22),
            array('NAGA', 22),
            array('OSLOB', 22),
            array('PILAR', 22),
            array('PINAMUNGAHAN', 22),
            array('PORO', 22),
            array('RONDA', 22),
            array('SAMBOAN', 22),
            array('SAN FERNANDO', 22),
            array('SAN FRANCISCO', 22),
            array('SAN REMIGIO', 22),
            array('SANTA FE', 22),
            array('SANTANDER', 22),
            array('SIBONGA', 22),
            array('SOGOD', 22),
            array('TABOGON', 22),
            array('TABUELAN', 22),
            array('CITY OF TALISAY', 22),
            array('TOLEDO CITY', 22),
            array('TUBURAN', 22),
            array('TUDELA', 22),
            array('AMLAN', 46),
            array('AYUNGON', 46),
            array('BACONG', 46),
            array('BAIS CITY', 46),
            array('BASAY', 46),
            array('CITY OF BAYAWAN', 46),
            array('BINDOY', 46),
            array('CANLAON CITY', 46),
            array('DAUIN', 46),
            array('DUMAGUETE CITY', 46),
            array('GUIHULNGAN', 46),
            array('JIMALALUD', 46),
            array('LA LIBERTAD', 46),
            array('MABINAY', 46),
            array('MANJUYOD', 46),
            array('PAMPLONA', 46),
            array('SAN JOSE', 46),
            array('SANTA CATALINA', 46),
            array('SIATON', 46),
            array('SIBULAN', 46),
            array('CITY OF TANJAY', 46),
            array('TAYASAN', 46),
            array('VALENCIA', 46),
            array('VALLEHERMOSO', 46),
            array('ZAMBOANGUITA', 46),
            array('ENRIQUE VILLANUEVA', 61),
            array('LARENA', 61),
            array('LAZI', 61),
            array('MARIA', 61),
            array('SAN JUAN', 61),
            array('SIQUIJOR', 61),
            array('ARTECHE', 26),
            array('BALANGIGA', 26),
            array('BALANGKAYAN', 26),
            array('BORONGAN', 26),
            array('CAN-AVID', 26),
            array('DOLORES', 26),
            array('GENERAL MACARTHUR', 26),
            array('GIPORLOS', 26),
            array('GUIUAN', 26),
            array('HERNANI', 26),
            array('JIPAPAD', 26),
            array('LAWAAN', 26),
            array('LLORENTE', 26),
            array('MASLOG', 26),
            array('MAYDOLONG', 26),
            array('MERCEDES', 26),
            array('ORAS', 26),
            array('QUINAPONDAN', 26),
            array('SALCEDO', 26),
            array('SAN JULIAN', 26),
            array('SAN POLICARPO', 26),
            array('SULAT', 26),
            array('TAFT', 26),
            array('ABUYOG', 37),
            array('ALANGALANG', 37),
            array('ALBUERA', 37),
            array('BABATNGON', 37),
            array('BARUGO', 37),
            array('BATO', 37),
            array('BAYBAY', 37),
            array('BURAUEN', 37),
            array('CALUBIAN', 37),
            array('CAPOOCAN', 37),
            array('CARIGARA', 37),
            array('DAGAMI', 37),
            array('DULAG', 37),
            array('HILONGOS', 37),
            array('HINDANG', 37),
            array('INOPACAN', 37),
            array('ISABEL', 37),
            array('JARO', 37),
            array('JAVIER', 37),
            array('JULITA', 37),
            array('KANANGA', 37),
            array('LA PAZ', 37),
            array('LEYTE', 37),
            array('MACARTHUR', 37),
            array('MAHAPLAG', 37),
            array('MATAG-OB', 37),
            array('MATALOM', 37),
            array('MAYORGA', 37),
            array('MERIDA', 37),
            array('ORMOC CITY', 37),
            array('PALO', 37),
            array('PALOMPON', 37),
            array('PASTRANA', 37),
            array('SAN ISIDRO', 37),
            array('SAN MIGUEL', 37),
            array('SANTA FE', 37),
            array('TABANGO', 37),
            array('TABONTABON', 37),
            array('TACLOBAN CITY', 37),
            array('TANAUAN', 37),
            array('TOLOSA', 37),
            array('TUNGA', 37),
            array('VILLABA', 37),
            array('ALLEN', 48),
            array('BIRI', 48),
            array('BOBON', 48),
            array('CAPUL', 48),
            array('CATARMAN', 48),
            array('CATUBIG', 48),
            array('GAMAY', 48),
            array('LAOANG', 48),
            array('LAPINIG', 48),
            array('LAS NAVAS', 48),
            array('LAVEZARES', 48),
            array('MAPANAS', 48),
            array('MONDRAGON', 48),
            array('PALAPAG', 48),
            array('PAMBUJAN', 48),
            array('ROSARIO', 48),
            array('SAN ANTONIO', 48),
            array('SAN ISIDRO', 48),
            array('SAN JOSE', 48),
            array('SAN ROQUE', 48),
            array('SAN VICENTE', 48),
            array('SILVINO LOBOS', 48),
            array('VICTORIA', 48),
            array('LOPE DE VEGA', 48),
            array('ALMAGRO', 60),
            array('BASEY', 60),
            array('CALBAYOG CITY', 60),
            array('CALBIGA', 60),
            array('CATBALOGAN', 60),
            array('DARAM', 60),
            array('GANDARA', 60),
            array('HINABANGAN', 60),
            array('JIABONG', 60),
            array('MARABUT', 60),
            array('MATUGUINAO', 60),
            array('MOTIONG', 60),
            array('PINABACDAO', 60),
            array('SAN JOSE DE BUAN', 60),
            array('SAN SEBASTIAN', 60),
            array('SANTA MARGARITA', 60),
            array('SANTA RITA', 60),
            array('SANTO NIÑO', 60),
            array('TALALORA', 60),
            array('TARANGNAN', 60),
            array('VILLAREAL', 60),
            array('PARANAS', 60),
            array('ZUMARRAGA', 60),
            array('TAGAPUL-AN', 60),
            array('SAN JORGE', 60),
            array('PAGSANGHAN', 60),
            array('ANAHAWAN', 64),
            array('BONTOC', 64),
            array('HINUNANGAN', 64),
            array('HINUNDAYAN', 64),
            array('LIBAGON', 64),
            array('LILOAN', 64),
            array('CITY OF MAASIN', 64),
            array('MACROHON', 64),
            array('MALITBOG', 64),
            array('PADRE BURGOS', 64),
            array('PINTUYAN', 64),
            array('SAINT BERNARD', 64),
            array('SAN FRANCISCO', 64),
            array('SAN JUAN', 64),
            array('SAN RICARDO', 64),
            array('SILAGO', 64),
            array('SOGOD', 64),
            array('TOMAS OPPUS', 64),
            array('LIMASAWA', 64),
            array('ALMERIA', 78),
            array('BILIRAN', 78),
            array('CABUCGAYAN', 78),
            array('CAIBIRAN', 78),
            array('CULABA', 78),
            array('KAWAYAN', 78),
            array('MARIPIPI', 78),
            array('NAVAL', 78),
            array('DAPITAN CITY', 72),
            array('DIPOLOG CITY', 72),
            array('KATIPUNAN', 72),
            array('LA LIBERTAD', 72),
            array('LABASON', 72),
            array('LILOY', 72),
            array('MANUKAN', 72),
            array('MUTIA', 72),
            array('PIÑAN', 72),
            array('POLANCO', 72),
            array('PRES. MANUEL A. ROXAS', 72),
            array('RIZAL', 72),
            array('SALUG', 72),
            array('SERGIO OSMEÑA SR.', 72),
            array('SIAYAN', 72),
            array('SIBUCO', 72),
            array('SIBUTAD', 72),
            array('SINDANGAN', 72),
            array('SIOCON', 72),
            array('SIRAWAI', 72),
            array('TAMPILISAN', 72),
            array('JOSE DALMAN', 72),
            array('GUTALAC', 72),
            array('BALIGUIAN', 72),
            array('GODOD', 72),
            array('BACUNGAN', 72),
            array('KALAWIT', 72),
            array('AURORA', 73),
            array('BAYOG', 73),
            array('DIMATALING', 73),
            array('DINAS', 73),
            array('DUMALINAO', 73),
            array('DUMINGAG', 73),
            array('KUMALARANG', 73),
            array('LABANGAN', 73),
            array('LAPUYAN', 73),
            array('MAHAYAG', 73),
            array('MARGOSATUBIG', 73),
            array('MIDSALIP', 73),
            array('MOLAVE', 73),
            array('PAGADIAN CITY', 73),
            array('RAMON MAGSAYSAY', 73),
            array('SAN MIGUEL', 73),
            array('SAN PABLO', 73),
            array('TABINA', 73),
            array('TAMBULIG', 73),
            array('TUKURAN', 73),
            array('ZAMBOANGA CITY', 73),
            array('LAKEWOOD', 73),
            array('JOSEFINA', 73),
            array('PITOGO', 73),
            array('SOMINOT', 73),
            array('VINCENZO A. SAGUN', 73),
            array('GUIPOS', 73),
            array('TIGBAO', 73),
            array('ALICIA', 83),
            array('BUUG', 83),
            array('DIPLAHAN', 83),
            array('IMELDA', 83),
            array('IPIL', 83),
            array('KABASALAN', 83),
            array('MABUHAY', 83),
            array('MALANGAS', 83),
            array('NAGA', 83),
            array('OLUTANGA', 83),
            array('PAYAO', 83),
            array('ROSELLER LIM', 83),
            array('SIAY', 83),
            array('TALUSAN', 83),
            array('TITAY', 83),
            array('TUNGAWAN', 83),
            array('CITY OF ISABELA', 97),
            array('BAUNGON', 13),
            array('DAMULOG', 13),
            array('DANGCAGAN', 13),
            array('DON CARLOS', 13),
            array('IMPASUG-ONG', 13),
            array('KADINGILAN', 13),
            array('KALILANGAN', 13),
            array('KIBAWE', 13),
            array('KITAOTAO', 13),
            array('LANTAPAN', 13),
            array('LIBONA', 13),
            array('CITY OF MALAYBALAY', 13),
            array('MALITBOG', 13),
            array('MANOLO FORTICH', 13),
            array('MARAMAG', 13),
            array('PANGANTUCAN', 13),
            array('QUEZON', 13),
            array('SAN FERNANDO', 13),
            array('SUMILAO', 13),
            array('TALAKAG', 13),
            array('CITY OF VALENCIA', 13),
            array('CABANGLASAN', 13),
            array('CATARMAN', 18),
            array('GUINSILIBAN', 18),
            array('MAHINOG', 18),
            array('MAMBAJAO', 18),
            array('SAGAY', 18),
            array('BACOLOD', 35),
            array('BALOI', 35),
            array('BAROY', 35),
            array('ILIGAN CITY', 35),
            array('KAPATAGAN', 35),
            array('SULTAN NAGA DIMAPORO', 35),
            array('KAUSWAGAN', 35),
            array('KOLAMBUGAN', 35),
            array('LALA', 35),
            array('LINAMON', 35),
            array('MAGSAYSAY', 35),
            array('MAIGO', 35),
            array('MATUNGAO', 35),
            array('MUNAI', 35),
            array('NUNUNGAN', 35),
            array('PANTAO RAGAT', 35),
            array('POONA PIAGAPO', 35),
            array('SALVADOR', 35),
            array('SAPAD', 35),
            array('TAGOLOAN', 35),
            array('TANGCAL', 35),
            array('TUBOD', 35),
            array('PANTAR', 35),
            array('ALORAN', 42),
            array('BALIANGAO', 42),
            array('BONIFACIO', 42),
            array('CALAMBA', 42),
            array('CLARIN', 42),
            array('CONCEPCION', 42),
            array('JIMENEZ', 42),
            array('LOPEZ JAENA', 42),
            array('OROQUIETA CITY', 42),
            array('OZAMIS CITY', 42),
            array('PANAON', 42),
            array('PLARIDEL', 42),
            array('SAPANG DALAGA', 42),
            array('SINACABAN', 42),
            array('TANGUB CITY', 42),
            array('TUDELA', 42),
            array('DON VICTORIANO CHIONGBIAN', 42),
            array('ALUBIJID', 43),
            array('BALINGASAG', 43),
            array('BALINGOAN', 43),
            array('BINUANGAN', 43),
            array('CAGAYAN DE ORO CITY', 43),
            array('CLAVERIA', 43),
            array('EL SALVADOR', 43),
            array('GINGOOG CITY', 43),
            array('GITAGUM', 43),
            array('INITAO', 43),
            array('JASAAN', 43),
            array('KINOGUITAN', 43),
            array('LAGONGLONG', 43),
            array('LAGUINDINGAN', 43),
            array('LIBERTAD', 43),
            array('LUGAIT', 43),
            array('MAGSAYSAY', 43),
            array('MANTICAO', 43),
            array('MEDINA', 43),
            array('NAAWAN', 43),
            array('OPOL', 43),
            array('SALAY', 43),
            array('SUGBONGCOGON', 43),
            array('TAGOLOAN', 43),
            array('TALISAYAN', 43),
            array('VILLANUEVA', 43),
            array('ASUNCION', 23),
            array('CARMEN', 23),
            array('KAPALONG', 23),
            array('NEW CORELLA', 23),
            array('CITY OF PANABO', 23),
            array('ISLAND GARDEN CITY OF SAMAL', 23),
            array('SANTO TOMAS', 23),
            array('CITY OF TAGUM', 23),
            array('TALAINGOD', 23),
            array('BRAULIO E. DUJALI', 23),
            array('SAN ISIDRO', 23),
            array('BANSALAN', 24),
            array('DAVAO CITY', 24),
            array('CITY OF DIGOS', 24),
            array('HAGONOY', 24),
            array('JOSE ABAD SANTOS', 24),
            array('KIBLAWAN', 24),
            array('MAGSAYSAY', 24),
            array('MALALAG', 24),
            array('MALITA', 24),
            array('MATANAO', 24),
            array('PADADA', 24),
            array('SANTA CRUZ', 24),
            array('SANTA MARIA', 24),
            array('SULOP', 24),
            array('SARANGANI', 24),
            array('DON MARCELINO', 24),
            array('BAGANGA', 25),
            array('BANAYBANAY', 25),
            array('BOSTON', 25),
            array('CARAGA', 25),
            array('CATEEL', 25),
            array('GOVERNOR GENEROSO', 25),
            array('LUPON', 25),
            array('MANAY', 25),
            array('MATI', 25),
            array('SAN ISIDRO', 25),
            array('TARRAGONA', 25),
            array('COMPOSTELA', 82),
            array('LAAK', 82),
            array('MABINI', 82),
            array('MACO', 82),
            array('MARAGUSAN', 82),
            array('MAWAB', 82),
            array('MONKAYO', 82),
            array('MONTEVISTA', 82),
            array('NABUNTURAN', 82),
            array('NEW BATAAN', 82),
            array('PANTUKAN', 82),
            array('ALAMADA', 47),
            array('CARMEN', 47),
            array('KABACAN', 47),
            array('CITY OF KIDAPAWAN', 47),
            array('LIBUNGAN', 47),
            array('MAGPET', 47),
            array('MAKILALA', 47),
            array('MATALAM', 47),
            array('MIDSAYAP', 47),
            array('M\'LANG', 47),
            array('PIGKAWAYAN', 47),
            array('PIKIT', 47),
            array('PRESIDENT ROXAS', 47),
            array('TULUNAN', 47),
            array('ANTIPAS', 47),
            array('BANISILAN', 47),
            array('ALEOSAN', 47),
            array('ARAKAN', 47),
            array('BANGA', 63),
            array('GENERAL SANTOS CITY', 63),
            array('CITY OF KORONADAL', 63),
            array('NORALA', 63),
            array('POLOMOLOK', 63),
            array('SURALLAH', 63),
            array('TAMPAKAN', 63),
            array('TANTANGAN', 63),
            array('T\'BOLI', 63),
            array('TUPI', 63),
            array('SANTO NIÑO', 63),
            array('LAKE SEBU', 63),
            array('BAGUMBAYAN', 65),
            array('COLUMBIO', 65),
            array('ESPERANZA', 65),
            array('ISULAN', 65),
            array('KALAMANSIG', 65),
            array('LEBAK', 65),
            array('LUTAYAN', 65),
            array('LAMBAYONG', 65),
            array('PALIMBANG', 65),
            array('PRESIDENT QUIRINO', 65),
            array('CITY OF TACURONG', 65),
            array('SEN. NINOY AQUINO', 65),
            array('ALABEL', 80),
            array('GLAN', 80),
            array('KIAMBA', 80),
            array('MAASIM', 80),
            array('MAITUM', 80),
            array('MALAPATAN', 80),
            array('MALUNGON', 80),
            array('COTABATO CITY', 98),
            array('TONDO I/II', 39),
            array('BINONDO', 39),
            array('QUIAPO', 39),
            array('SAN NICOLAS', 39),
            array('SANTA CRUZ', 39),
            array('SAMPALOC', 39),
            array('SAN MIGUEL', 39),
            array('ERMITA', 39),
            array('INTRAMUROS', 39),
            array('MALATE', 39),
            array('PACO', 39),
            array('PANDACAN', 39),
            array('PORT AREA', 39),
            array('SANTA ANA', 39),
            array('CITY OF MANDALUYONG', 74),
            array('CITY OF MARIKINA', 74),
            array('CITY OF PASIG', 74),
            array('QUEZON CITY', 74),
            array('CITY OF SAN JUAN', 74),
            array('CALOOCAN CITY', 75),
            array('CITY OF MALABON', 75),
            array('CITY OF NAVOTAS', 75),
            array('CITY OF VALENZUELA', 75),
            array('CITY OF LAS PIÑAS', 76),
            array('CITY OF MAKATI', 76),
            array('CITY OF MUNTINLUPA', 76),
            array('CITY OF PARAÑAQUE', 76),
            array('PASAY CITY', 76),
            array('PATEROS', 76),
            array('TAGUIG CITY', 76),
            array('BANGUED', 1),
            array('BOLINEY', 1),
            array('BUCAY', 1),
            array('BUCLOC', 1),
            array('DAGUIOMAN', 1),
            array('DANGLAS', 1),
            array('DOLORES', 1),
            array('LA PAZ', 1),
            array('LACUB', 1),
            array('LAGANGILANG', 1),
            array('LAGAYAN', 1),
            array('LANGIDEN', 1),
            array('LICUAN-BAAY', 1),
            array('LUBA', 1),
            array('MALIBCONG', 1),
            array('MANABO', 1),
            array('PEÑARRUBIA', 1),
            array('PIDIGAN', 1),
            array('PILAR', 1),
            array('SALLAPADAN', 1),
            array('SAN ISIDRO', 1),
            array('SAN JUAN', 1),
            array('SAN QUINTIN', 1),
            array('TAYUM', 1),
            array('TINEG', 1),
            array('TUBO', 1),
            array('VILLAVICIOSA', 1),
            array('ATOK', 11),
            array('BAGUIO CITY', 11),
            array('BAKUN', 11),
            array('BOKOD', 11),
            array('BUGUIAS', 11),
            array('ITOGON', 11),
            array('KABAYAN', 11),
            array('KAPANGAN', 11),
            array('KIBUNGAN', 11),
            array('LA TRINIDAD', 11),
            array('MANKAYAN', 11),
            array('SABLAN', 11),
            array('TUBA', 11),
            array('TUBLAY', 11),
            array('BANAUE', 27),
            array('HUNGDUAN', 27),
            array('KIANGAN', 27),
            array('LAGAWE', 27),
            array('LAMUT', 27),
            array('MAYOYAO', 27),
            array('ALFONSO LISTA', 27),
            array('AGUINALDO', 27),
            array('HINGYON', 27),
            array('TINOC', 27),
            array('ASIPULO', 27),
            array('BALBALAN', 32),
            array('LUBUAGAN', 32),
            array('PASIL', 32),
            array('PINUKPUK', 32),
            array('RIZAL', 32),
            array('TABUK', 32),
            array('TANUDAN', 32),
            array('TINGLAYAN', 32),
            array('BARLIG', 44),
            array('BAUKO', 44),
            array('BESAO', 44),
            array('BONTOC', 44),
            array('NATONIN', 44),
            array('PARACELIS', 44),
            array('SABANGAN', 44),
            array('SADANGA', 44),
            array('SAGADA', 44),
            array('TADIAN', 44),
            array('CALANASAN', 81),
            array('CONNER', 81),
            array('FLORA', 81),
            array('KABUGAO', 81),
            array('LUNA', 81),
            array('PUDTOL', 81),
            array('SANTA MARCELA', 81),
            array('LAMITAN', 7),
            array('LANTAWAN', 7),
            array('MALUSO', 7),
            array('SUMISIP', 7),
            array('TIPO-TIPO', 7),
            array('TUBURAN', 7),
            array('AKBAR', 7),
            array('AL-BARKA', 7),
            array('HADJI MOHAMMAD AJUL', 7),
            array('UNGKAYA PUKAN', 7),
            array('HADJI MUHTAMAD', 7),
            array('TABUAN-LASA', 7),
            array('BACOLOD-KALAWI', 36),
            array('BALABAGAN', 36),
            array('BALINDONG', 36),
            array('BAYANG', 36),
            array('BINIDAYAN', 36),
            array('BUBONG', 36),
            array('BUTIG', 36),
            array('GANASSI', 36),
            array('KAPAI', 36),
            array('LUMBA-BAYABAO', 36),
            array('LUMBATAN', 36),
            array('MADALUM', 36),
            array('MADAMBA', 36),
            array('MALABANG', 36),
            array('MARANTAO', 36),
            array('MARAWI CITY', 36),
            array('MASIU', 36),
            array('MULONDO', 36),
            array('PAGAYAWAN', 36),
            array('PIAGAPO', 36),
            array('POONA BAYABAO', 36),
            array('PUALAS', 36),
            array('DITSAAN-RAMAIN', 36),
            array('SAGUIARAN', 36),
            array('TAMPARAN', 36),
            array('TARAKA', 36),
            array('TUBARAN', 36),
            array('TUGAYA', 36),
            array('WAO', 36),
            array('MAROGONG', 36),
            array('CALANOGAS', 36),
            array('BUADIPOSO-BUNTONG', 36),
            array('MAGUING', 36),
            array('PICONG', 36),
            array('LUMBAYANAGUE', 36),
            array('BUMBARAN', 36),
            array('TAGOLOAN II', 36),
            array('KAPATAGAN', 36),
            array('SULTAN DUMALONDONG', 36),
            array('LUMBACAUNAYAN', 36),
            array('AMPATUAN', 38),
            array('BULDON', 38),
            array('BULUAN', 38),
            array('DATU PAGLAS', 38),
            array('DATU PIANG', 38),
            array('DATU ODIN SINSUAT', 38),
            array('SHARIFF AGUAK', 38),
            array('MATANOG', 38),
            array('PAGALUNGAN', 38),
            array('PARANG', 38),
            array('SULTAN KUDARAT', 38),
            array('SULTAN SA BARONGIS', 38),
            array('KABUNTALAN', 38),
            array('UPI', 38),
            array('TALAYAN', 38),
            array('SOUTH UPI', 38),
            array('BARIRA', 38),
            array('GEN. S. K. PENDATUN', 38),
            array('MAMASAPANO', 38),
            array('TALITAY', 38),
            array('PAGAGAWAN', 38),
            array('PAGLAT', 38),
            array('SULTAN MASTURA', 38),
            array('GUINDULUNGAN', 38),
            array('DATU SAUDI-AMPATUAN', 38),
            array('DATU UNSAY', 38),
            array('DATU ABDULLAH SANKI', 38),
            array('RAJAH BUAYAN', 38),
            array('DATU BLAH T. SINSUAT', 38),
            array('DATU ANGGAL MIDTIMBANG', 38),
            array('MANGUDADATU', 38),
            array('PANDAG', 38),
            array('NORTHERN KABUNTALAN', 38),
            array('DATU HOFFER AMPATUAN', 38),
            array('DATU SALIBO', 38),
            array('SHARIFF SAYDONA MUSTAPHA', 38),
            array('INDANAN', 66),
            array('JOLO', 66),
            array('KALINGALAN CALUANG', 66),
            array('LUUK', 66),
            array('MAIMBUNG', 66),
            array('HADJI PANGLIMA TAHIL', 66),
            array('OLD PANAMAO', 66),
            array('PANGUTARAN', 66),
            array('PARANG', 66),
            array('PATA', 66),
            array('PATIKUL', 66),
            array('SIASI', 66),
            array('TALIPAO', 66),
            array('TAPUL', 66),
            array('TONGKIL', 66),
            array('PANGLIMA ESTINO', 66),
            array('LUGUS', 66),
            array('PANDAMI', 66),
            array('OMAR', 66),
            array('PANGLIMA SUGALA', 70),
            array('BONGAO', 70),
            array('MAPUN', 70),
            array('SIMUNUL', 70),
            array('SITANGKAI', 70),
            array('SOUTH UBIAN', 70),
            array('TANDUBAS', 70),
            array('TURTLE ISLANDS', 70),
            array('LANGUYAN', 70),
            array('SAPA-SAPA', 70),
            array('SIBUTU', 70),
            array('BUENAVISTA', 2),
            array('BUTUAN CITY', 2),
            array('CABADBARAN', 2),
            array('CARMEN', 2),
            array('JABONGA', 2),
            array('KITCHARAO', 2),
            array('LAS NIEVES', 2),
            array('MAGALLANES', 2),
            array('NASIPIT', 2),
            array('SANTIAGO', 2),
            array('TUBAY', 2),
            array('REMEDIOS T. ROMUALDEZ', 2),
            array('BAYUGAN', 3),
            array('BUNAWAN', 3),
            array('ESPERANZA', 3),
            array('LA PAZ', 3),
            array('LORETO', 3),
            array('PROSPERIDAD', 3),
            array('ROSARIO', 3),
            array('SAN FRANCISCO', 3),
            array('SAN LUIS', 3),
            array('SANTA JOSEFA', 3),
            array('TALACOGON', 3),
            array('TRENTO', 3),
            array('VERUELA', 3),
            array('SIBAGAT', 3),
            array('ALEGRIA', 67),
            array('BACUAG', 67),
            array('BURGOS', 67),
            array('CLAVER', 67),
            array('DAPA', 67),
            array('DEL CARMEN', 67),
            array('GENERAL LUNA', 67),
            array('GIGAQUIT', 67),
            array('MAINIT', 67),
            array('MALIMONO', 67),
            array('PILAR', 67),
            array('PLACER', 67),
            array('SAN BENITO', 67),
            array('SAN FRANCISCO', 67),
            array('SAN ISIDRO', 67),
            array('SANTA MONICA', 67),
            array('SISON', 67),
            array('SOCORRO', 67),
            array('SURIGAO CITY', 67),
            array('TAGANA-AN', 67),
            array('TUBOD', 67),
            array('BAROBO', 68),
            array('BAYABAS', 68),
            array('CITY OF BISLIG', 68),
            array('CAGWAIT', 68),
            array('CANTILAN', 68),
            array('CARMEN', 68),
            array('CARRASCAL', 68),
            array('CORTES', 68),
            array('HINATUAN', 68),
            array('LANUZA', 68),
            array('LIANGA', 68),
            array('LINGIG', 68),
            array('MADRID', 68),
            array('MARIHATAG', 68),
            array('SAN AGUSTIN', 68),
            array('SAN MIGUEL', 68),
            array('TAGBINA', 68),
            array('TAGO', 68),
            array('TANDAG', 68),
            array('BASILISA', 85),
            array('CAGDIANAO', 85),
            array('DINAGAT', 85),
            array('LIBJO', 85),
            array('LORETO', 85),
            array('SAN JOSE', 85),
            array('TUBAJON', 85),
            array('BOAC', 40),
            array('BUENAVISTA', 40),
            array('GASAN', 40),
            array('MOGPOG', 40),
            array('SANTA CRUZ', 40),
            array('TORRIJOS', 40),
            array('ABRA DE ILOG', 51),
            array('CALINTAAN', 51),
            array('LOOC', 51),
            array('LUBANG', 51),
            array('MAGSAYSAY', 51),
            array('MAMBURAO', 51),
            array('PALUAN', 51),
            array('RIZAL', 51),
            array('SABLAYAN', 51),
            array('SAN JOSE', 51),
            array('SANTA CRUZ', 51),
            array('BACO', 52),
            array('BANSUD', 52),
            array('BONGABONG', 52),
            array('BULALACAO', 52),
            array('CITY OF CALAPAN', 52),
            array('GLORIA', 52),
            array('MANSALAY', 52),
            array('NAUJAN', 52),
            array('PINAMALAYAN', 52),
            array('POLA', 52),
            array('PUERTO GALERA', 52),
            array('ROXAS', 52),
            array('SAN TEODORO', 52),
            array('SOCORRO', 52),
            array('VICTORIA', 52),
            array('ABORLAN', 53),
            array('AGUTAYA', 53),
            array('ARACELI', 53),
            array('BALABAC', 53),
            array('BATARAZA', 53),
            array('BROOKE\'S POINT', 53),
            array('BUSUANGA', 53),
            array('CAGAYANCILLO', 53),
            array('CORON', 53),
            array('CUYO', 53),
            array('DUMARAN', 53),
            array('EL NIDO', 53),
            array('LINAPACAN', 53),
            array('MAGSAYSAY', 53),
            array('NARRA', 53),
            array('PUERTO PRINCESA CITY', 53),
            array('QUEZON', 53),
            array('ROXAS', 53),
            array('SAN VICENTE', 53),
            array('TAYTAY', 53),
            array('KALAYAAN', 53),
            array('CULION', 53),
            array('RIZAL', 53),
            array('SOFRONIO ESPAÑOLA', 53),
            array('ALCANTARA', 59),
            array('BANTON', 59),
            array('CAJIDIOCAN', 59),
            array('CALATRAVA', 59),
            array('CONCEPCION', 59),
            array('CORCUERA', 59),
            array('LOOC', 59),
            array('MAGDIWANG', 59),
            array('ODIONGAN', 59),
            array('ROMBLON', 59),
            array('SAN AGUSTIN', 59),
            array('SAN ANDRES', 59),
            array('SAN FERNANDO', 59),
            array('SAN JOSE', 59),
            array('SANTA FE', 59),
            array('FERROL', 59),
            array('SANTA MARIA', 59)
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable($this->tableName());
    }
}